### ISSUE TITLE
Can't access Firestore from Flutter

### ISSUE THREAD

**Issue by mkiisoft** [tekartik/firebase.dart#7]
Like the title saids... I'm not getting firestore() method from Flutter
import 'package:tekartik_firebase_flutter/firebase_flutter.dart';

**Comment by alextekartik** [comment]
Firestore access is actually in a separate package: https://github.com/tekartik/firebase_firestore.dart

**Comment by mkiisoft** [comment]
Oh, thanks! Do you think this could work with Flutter on desktop?! (The embedded one to work in Windows, Mac, etc)

**Comment by alextekartik** [comment]
I have not tried flutter on desktop and don't know what will be the plugin support for it so I cannot answer yet...we'll see!

**Comment by Arno-Z** [comment]
My assumption would be it does not work. The FlutterFire components use the Android (Java/Gradle) or iOS (Cocao) native Firebase components for communication bwith Firebase.

A possible option for you may be to use CrossFire, bit the last time I took a look that still lacked Firebase Auth support. Maybe there are other Firebase connection packages out there which connect straight to the Firebase API's.

Happy coding!

**Comment by mkiisoft** [comment]
@Arno-Z a full Dart implementation without using Channels should be the way to go. Not sure if Google it's currently working on it but I was digging into all the Firebase dart implementatios.
